site_name: Physical Constants Dictionary (PCD)
site_description: YAML dictionary of physical constants and tools to create consistent constant sets for Earth System Models
site_author: ICAMS-US
repo_url: https://github.com/ICAMS-US/PhysicalConstantsDictionary
repo_name: ICAMS-US/PhysicalConstantsDictionary

# Navigation structure
nav:
  - Home: index.md
  - Dictionary Syntax: dictionary-syntax.md
  - CPCD Parser: cpcd-parser.md

# Theme configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

# Documentation directory
docs_dir: docs

# Build directory
site_dir: site

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ESCOMP/PhysicalConstantsDictionary
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; ICAMS
